import Head from 'next/head';
import Nav from 'components/Nav/Nav';
import Header from 'components/Brands/Header/Header';
import Description from 'components/Brands/Description/Description';
import Subscribe from 'components/Brands/Subscribe/Subscribe';
import Footer from 'components/Footer/Footer';

function Brands({ toast }) {
  return (
    <div>
      <Head>
        <title>Brands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/fav.png" />
      </Head>
      <Nav />
      <Header />
      <Description />
      <Subscribe toast={toast}/>
      <Footer />
    </div>
  );
}

export default Brands;
