import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import sanityClient from 'sanity-client';
import homeStyles from 'styles/Home.module.scss';
import contentStyles from 'styles/Content.module.css';

export default function Content() {
  const [loading, setLoading] = useState(true);
  const [allMovies, setAllMovies] = useState([]);

  useEffect(() => {
    sanityClient
      .fetch(
        `*[_type == "movie"] {
          ...,
          "posterUrl": poster.asset->url
      }`
      )
      .then((data) => {
        setLoading(false);
        setAllMovies(data);
      })
      .catch(console.error);
  }, []);

  return (
    <div className={homeStyles.container}>
      <Head>
        <title>Content</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={homeStyles.main}>
        <h1 className={homeStyles.title}>
          Here is some dummy data you can edit in{' '}
          <a href="https://nohbo-content.sanity.studio/" target="_blank" rel="noreferrer">
            Studio
          </a>
        </h1>

        <div
          style={{
            marginTop: '10px',
          }}
        >
          <Link href="/">
            <a
              style={{
                color: '#0070f3',
                textDecoration: 'none',
                fontWeight: 'bold',
                fontSize: '20px',
              }}
            >
              ← Back
            </a>
          </Link>
        </div>

        <div style={{ marginTop: '20px', display: 'flex', flexWrap: 'wrap', justifyContent: 'space-around' }}>
          {loading ? (
            <div>Loading...</div>
          ) : (
            allMovies.map((movie) => (
              <div className={contentStyles.movieItem} key={movie.title}>
                <p>{movie.title}</p>
                <div style={{ borderRadius: '5px' }}>
                  <Image
                    className={contentStyles.movieImage}
                    src={movie.posterUrl}
                    alt="Poster"
                    width={180}
                    height={250}
                    objectFit="cover"
                  />
                </div>
              </div>
            ))
          )}
        </div>
      </main>

      <footer className={homeStyles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={homeStyles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
