import { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import sanityClient from 'sanity-client';
import styles from '../styles/Home.module.css';

export default function Content() {
  const [allMovies, setAllMovies] = useState([]);

  useEffect(() => {
    sanityClient
      .fetch(`*[_type == "movie"]`)
      .then((data) => setAllMovies(data))
      .catch(console.error);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Content</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Here is some dummy data you can edit in Studio</h1>

        <div
          style={{
            marginTop: '10px',
          }}
        >
          <Link href="/">
            <a
              style={{
                color: '#0070f3',
                textDecoration: 'none',
                fontWeight: 'bold',
                fontSize: '20px',
              }}
            >
              ← Back
            </a>
          </Link>
        </div>

        <div style={{ marginTop: '20px' }}>
          {allMovies.map((movie) => (
            <div key={movie.title}>{movie.title}</div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
