import Head from 'next/head';
import Header from 'components/Home/Header/Header';
import Subheader from 'components/Home/Subheader/Subheader';
import Technologies from 'components/Home/Technoloies/Technologies';
import Products from 'components/Home/Products/Products';
import Philosophy from 'components/Home/Philosophy/Philosophy';
import Brand from 'components/Home/Brand/Brand';
import Buzz from 'components/Home/Buzz/Buzz';
import Subscribe from 'components/Brands/Subscribe/Subscribe';
import Contact from 'components/Home/Contact/Contact';
import Footer from 'components/Footer/Footer';

import styles from '../styles/Home.module.scss';

export default function Home({ toast }) {
  console.log('test new scope');
  return (
    <div style={{ overflow: 'hidden' }} className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Subheader />
      <Technologies />
      <Products />
      <Philosophy />
      <Brand />
      <Buzz />
      <Subscribe toast={toast} />
      <Contact />
      <Footer />
    </div>
  );
}
