import Head from 'next/head';
import Nav from 'components/Nav/Nav';
import Header from 'components/Press/Header/Header';
import List from 'components/Press/List/List';
import Footer from 'components/Footer/Footer';

function Press() {
  return (
    <div>
      <Head>
        <title>Press</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <List />
      <Footer />
    </div>
  );
}

export default Press;
