import Head from 'next/head';
import Nav from 'components/Nav/Nav';
import Header from 'components/Purpose/Header/Header';
import Description from 'components/Purpose/Description/Description';
import WeSave from 'components/Purpose/WeSave/WeSave';
import Subscribe from 'components/Brands/Subscribe/Subscribe';
import Contact from 'components/Home/Contact/Contact';
import Footer from 'components/Footer/Footer';

function Purpose({ toast }) {
  return (
    <div>
      <Head>
        <title>Purpose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/fav.png" />
      </Head>
      <Nav />
      <Header />
      <Description />
      <WeSave />
      <Subscribe toast={toast}/>
      <Contact />
      <Footer />
    </div>
  );
}

export default Purpose;
