import Head from 'next/head';
import Nav from 'components/Nav/Nav';
import Header from 'components/Team/Header/Header';
import Description from 'components/Team/Description/Description';
import Hiring from 'components/Team/Hiring/Hiring';
import Footer from 'components/Footer/Footer';

function Brands() {
  return (
    <div>
      <Head>
        <title>Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/fav.png" />
      </Head>
      <Nav />
      <Header />
      <Description />
      <Hiring />
      <Footer />
    </div>
  );
}

export default Brands;
