import Head from 'next/head';
import Nav from 'components/Nav/Nav';
import Header from 'components/Technology/Header/Header';
import Solutions from 'components/Technology/Solutions/Solutions';
import Contact from 'components/Home/Contact/Contact';
import Footer from 'components/Footer/Footer';

function Technology({ toast }) {
  return (
    <div>
      <Head>
        <title>Technology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Header />
      <Solutions />
      <Contact />
      <Footer />
    </div>
  );
}

export default Technology;
